# -*- coding: utf-8 -*-
"""Python practice

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uy0mN3iPkXHiquChs6cUQ1ud-Sb_HR2A
"""

# Flow control statement - looping statement

# Looping statement - used to task multiple times
# eg. song run till app close , filling bucket with mug of water until, full salary creted

# type of loop- 1) for loop  2) while loop

# While loop- run till condition true

# syntax
# while condition
# code

# code
i=1
while i<=4:
  print(i)
  i=i+1

# code
i=1
while i<=4:
  print(i)
  i=i+1

# code
i=1
while i<=9:
  print(i)
  i=i+1

# code
i=1
while i<=8:
  print(i)
  i=i+1

# code
i=1
while i<=6:
  print(i)
  i=i+2

# program to print table
n=2
i=1
while i<=10:
  print(n,"*",i,"=",n*i)
  i=i+1

# program to print table
n=2
i=1
while i<=10:
  print(n,"*",i,"=",n*i)
  i=i+1

# program to print table
n=2
i=1
while i<=10:
  print(n,"*",i,"=",n*i)
  i=i+1

# prime program number
n=int(input('enter number:'))
i=1
count=0
while i<=0:
  if i%n==0:
    count=1
  i=i+1
print(count)
if count==0:
  print('given number is prime number:')
else:
  print('given number is not prime number:')

# prime program number
n=int(input('enter number:'))
i=1
count=0
while i<=0:
  if i%n==0:
    count=1
  i=i+1
print(count)
if count==0:
  print('given number is prime number:')
else:
  print('given number is not prime number:')

# find th esum of 3 digit number enter by user(using while loop)
i=int(input('enter number:'))
sum=0
while(i>0):
  sum=sum+i%10
  i=i//10
print('sum of digit=',sum)

i=int(input('enter number:'))
sum=0
while(i>0):
  sum=sum+i%10
  i=i//10
print('sum of digit',sum)

i=int(input('enter number:'))
sum=0
while(i>0):
  sum=sum+i%10
  i=i//10
print('sum of digit',sum)

i=int(input('enter number:'))
sum=0
while(i>0):
  sum=sum+i%10
  i=i//10
print('sumof digit',sum)

i=int(input('enter number:'))
sum=0
while(i>0):
  sum=sum+i%10
  i=i//10
print('sum of digit',sum)

i=int(input('enter number:'))
sum=0
while(i>0):
  sum=sum+i%10
  i=i//10
print('sum of digit',sum)

i=int(input('enter number'))
sum=0
while (i>0):
  sum=sum+i%10
  i=i//10
print('sum of digit',sum)

i=int(input('enter number:'))
sum=0
while (i>0):
  sum=sum+i%10
  i=i//10
print('sum of digit',sum)

